mystr = "my name is Aakarshit Agarwal"
print(len(mystr))
print(mystr[::-1])
print(type(mystr))
print(mystr.endswith("Agarwal"))
print(mystr.count("a"))
print(mystr.capitalize())
print(mystr.find("is"))
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("is","are"))